### ISSUE TITLE
Fast deploy

### ISSUE THREAD

**Issue by bastnic** [antistatique/capdrupal#12]
I just tested capdrupal on a small d6 website : 
- i don't have features
- 90% of deployment consist of css / js / new stuff with no risk (change of template, new small hook). So not a big bakend dev but small fix on some existing website

It can be cool to not be forced to put the website in maintenance mode / offline

**Comment by gagarine** [comment]
Fixed. Taks are now separated.

**Comment by gido** [comment]
In release 0.10.0
