### ISSUE TITLE
Migrate to the drupal-deploy

### ISSUE THREAD

**Issue by gagarine** [antistatique/capdrupal#24]
A capistrano 3 gem is on https://github.com/capistrano/drupal-deploy. It's also listed on http://capistranorb.com/ . I hop it become some kind of "official" gem.

This gem is good for peoples that want to stay with capistrano 2. But we shouldn't we redirect most of them to https://github.com/capistrano/drupal-deploy?

I'm also to remove the D8 version because it doesn't works with new version of drupal 8. I will support D8 on drupal-deploy when D8 is more stable.

**Comment by gagarine** [comment]
@gido I mostly need your point of view.

**Comment by gagarine** [comment]
I made a pull request. In addition master branch should be deleted (only keep the d7 branch)

**Comment by rodrigoaguilera** [comment]
I haven't been able to even list the tasks from this recipes for d8. 
I look forward to see this happening

**Comment by gagarine** [comment]
Please follow the related issue on drupal-deploy https://github.com/capistrano/drupal-deploy/issues/1
