### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by eveyrat** [antistatique/capdrupal#32]
Hi,

I got an error requiring `capdrupal/capistrano` in the Capfile (Ruby 2.7.1) :

> cannot load such file -- capdrupal/capistrano

I could make it work by requiring `capdrupal` instead of `capdrupal/capistrano`. Not sure if the README is wrong or if something is wrong on my side.
I also noticed that the `deploy:setup` task doesn't seem to exist anymore. It may worth adjusting the README.

Thanks !

**Comment by WengerK** [comment]
You're right !

Many thanks for noticing this error. I obviously made an error when writing the README.
