### ISSUE TITLE
Backup database before code switch

### ISSUE THREAD

**Issue by gagarine** [antistatique/capdrupal#6]
Right after we put the site offline and before we switch to the new code do a backup (optional) this backup should be used in case of rollback.

**Comment by WengerK** [comment]
For Drupal 8, a database backup is done if you required it with the following code

```
  before :starting, "drupal:db:backup"
  before :failed, "drupal:db:rollback"
  before :cleanup, "drupal:db:backup:cleanup"
```

For Drupal 7, see the answer of @gido
